apps/conquers/urls.py
from django.conf.urls import url
from apps.conquers import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.user_login, name="login"),
    url(r'^logout$', views.user_logout, name="logout"),
    url(r'^actividad$', views.envio_actividad, name="activity")

]

usb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('apps.conquers.urls', namespace='conquers')),
]

apps/conquers/models.py
from django.db import models
from django.contrib.auth.models import User


class Comunity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    nickname = models.OneToOneField(User)
    nombre = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    comunity = models.ForeignKey(Comunity)
    options = ((1, 'Presidente'), (2, 'Auditor'))
    type_user = models.IntegerField(choices=options, default=1)

    def __str__(self):
        return self.nickname.username


class Activity(models.Model):
    comunity = models.ForeignKey(Comunity)
    fields = models.FileField(upload_to='archivos/')

    def __str__(self):
        return str(self.comunity)


class Nota(models.Model):
    comunity = models.ForeignKey(Comunity)
    activities = models.ForeignKey(Activity)
    puntuacion = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return str(self.comunity)

apps/conquers/forms.py
from django import forms
from django.contrib.auth.models import User
from apps.conquers import models

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class ProfileForm(forms.ModelForm):

    class Meta:
        model = models.UserProfile
        fields = ('nombre', 'last_name', 'type_user', 'comunity')


class ActivityForm(forms.ModelForm):

    class Meta:
        model = models.Activity
        fields = ('comunity', 'fields')

apps/conquers/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ProfileForm, ActivityForm
from .models import UserProfile, Activity

from django.http import HttpResponse


def valida(username):
    u = User.objects.get(username=username)
    up = UserProfile.objects.get(nickname=u)
    if up.type_user == 2:
        usu = 1
        return usu
    else:
        usu = 2
        return usu


def index(request):
    username = request.user.username
    if username == '':
        return render(request, 'conquers/index.html')
    else:
        usu = valida(username)
        print(usu)
        return render(request, 'conquers/index.html', {'tipo':usu })


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.nickname = user
            profile.save()
            registered = True

            return redirect('conquers:index')
        else:
            print("hay error")

    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'conquers/admin/registro.html', {'user': user_form,
                                                         'profile': profile_form, 'registrado': registered})


def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)

                return redirect('conquers:index')
            else:
                return HttpResponse("tu cuenta esta desactivada")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("login invalido")
    else:
        return render(request, 'conquers/admin/login.html', {})


def user_logout(request):
    logout(request)
    return redirect('conquers:index')


@login_required()
def envio_actividad(request):
    if request.method == 'POST':
        acty_form = ActivityForm(request.POST, request.FILES)
        if acty_form.is_valid():
            acty_form.save()

            return redirect('conquers:index')
        else:
            print("hay error")

    else:
        acty_form = ActivityForm()
    return render(request, 'conquers/admin/actividad.html', {'form':acty_form})

apps/conquers/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Name of project{% endblock title %}</title>
    {% block styles %}

    {% endblock styles %}
</head>
<body>
    {% block content %}

    {% endblock content %}
    {% block scripts %}

    {% endblock scripts %}
</body>
</html>

apps/conquers/templates/conquers/admin/actividad.html
{% extends "conquers/base_gastos.html" %}

{% block content %}


    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type= "submit" value="Enviar">
    </form>
    <a href="{% url 'conquers:index' %}">Volever</a>
{% endblock content %}

apps/conquers/templates/conquers/admin/login.html
{% extends "conquers/base_gastos.html" %}

{% block content %}


    <form method="post">
        {% csrf_token %}

        Username: <input type="text" name="username" value="" size="50" />
            <br />
        Password: <input type="password" name="password" value="" size="50" />
            <br />
        <input type= "submit" value="Registrar">
    </form>
    <a href="{% url 'conquers:index' %}">Volever</a>
{% endblock content %}

apps/conquers/templates/conquers/admin/registro.html
{% extends "conquers/base_gastos.html" %}

{% block content %}


    <form method="post">
        {% csrf_token %}
        {{ user.as_p }}
        {{ profile.as_p }}

        <input type= "submit" value="Registrar">
    </form>
    <a href="{% url 'conquers:index' %}">Volever</a>
{% endblock content %}

apps/conquers/templates/conquers/base_gastos.html
{% extends "base.html" %}

{% load staticfiles %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'conquers/css/gastos.css'  %}">
{% endblock styles %}

{% block scripts %}
   <script src="{% static 'conquers/js/gastos.js' %}"></script>
    {#<script src="{% static 'sapeim/js/vendor/hola.js' %}"></script>#}
{% endblock scripts %}

apps/conquers/templates/conquers/index.html
{% extends "conquers/base_gastos.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

    {% if user.is_authenticated %}
        <h1>hello {{ user.username }}!</h1>

        <a href="{% url 'conquers:logout' %}">Logout</a>
    {% else %}
        <h1>Hola!</h1>
        <a href="{% url 'conquers:register' %}">Registrarse</a>
        <a href="{% url 'conquers:login' %}">Login</a>

    {% endif %}
    {% if tipo == 1 %}
        <p>Menus</p>
    {% elif tipo == 2 %}
        <a href="{% url 'conquers:activity' %}">Envio de actividades</a>
    {% else %}
        <p>Menus</p>
    {% endif %}

{% endblock content %}